### ISSUE TITLE
Uranium Count

### ISSUE THREAD

**Issue by Oscar-IronTower** [vimontgames/bhktools#3]
Version 0.41

If you select and deselect the strategics checkbox, the uranium count is added again every time you do so.

**Comment by Benualdo** [comment]
Hi Oscar,
Thanks for reporting it. It has been fixed in commit [17aa2802046a58c6e7a301992c01e2fca6f97a77](https://github.com/vimontgames/bhktools/commit/17aa2802046a58c6e7a301992c01e2fca6f97a77)

**Comment by Benualdo** [comment]
I've a uploaded a build with the fix in case people have trouble compiling it themselves: [bhkmap 0.42](https://github.com/vimontgames/bhktools/releases/tag/0.42)
